name: qualtive_demo
description: Demo app for the qualtive plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  qualtive:
    path: ../qualtive

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
